CREATE TABLE FB_EVENT_DETAILS(
    EVENT_ID VARCHAR(25) NOT NULL PRIMARY KEY,
    NAME VARCHAR(500),
    CITY VARCHAR(200),
    PLACE VARCHAR(500),
    COUNTRY VARCHAR(200),
    ATTENDING_COUNT INTEGER,
    INTERESTED_COUNT INTEGER,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    START_DATE DATE,
    START_TIME TIME,
    END_DATE DATE,
    END_TIME TIME,
    URL VARCHAR(200),
    LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION LONG VARCHAR
);

CREATE TABLE FB_EVENT_ADMINS(
    EVENT_ID VARCHAR(25) NOT NULL,
    USER_ID VARCHAR(25) NOT NULL,
    CONSTRAINT PK_EVENT_ADMINS PRIMARY KEY (EVENT_ID, USER_ID)
);

CREATE TABLE FB_USER_IDENTITY(
    USER_ID VARCHAR(25) NOT NULL PRIMARY KEY,
    USER_DISPLAY_NAME VARCHAR(200),
    USER_URL VARCHAR(100)
);

CREATE TABLE FB_EVENT_REPORTSTATUS(
    EVENT_ID VARCHAR(25) NOT NULL PRIMARY KEY,
    REPORT_STATUS VARCHAR(10) NOT NULL DEFAULT 'NOT SENT',
    LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);